-- Seed baseline knowledge cards that describe the WorkPlanner AI assistant
-- itself — universal product knowledge true in every deployment (how @ai
-- personas / work-items / the knowledge base work). Runs on every fresh DB
-- (local, e2e test stack, and end-user deployments) so the KB is never empty.
--
-- NOT seeded here: work-planner *development* knowledge (repo layout, data
-- model, dev conventions, make targets, deploy internals) — that's only
-- relevant to work-planner contributors and would mislead an end-user's
-- personas working on their own projects.
--
-- ON CONFLICT DO NOTHING: idempotent — seeds fresh DBs, never clobbers a DB
-- where these slugs already exist (e.g. the dev/prod KB).

INSERT INTO knowledge_cards (id, content, tags, is_valid, created_at, updated_at)
VALUES
  ('ai-orchestration-overview', 'How the AI system works end to end: a user (or the ai-manager) posts an @ai-<persona> comment on a task. The ai-poller (Python, on Railway) detects the mention, creates a WorkItem, and a second poller dispatches it to claude-proxy (on the user''s Mac, using a Claude Max subscription). claude-proxy runs `claude -p` as that persona; the reply is posted back as a threaded comment. Personas: engineer, manager, planner, reviewer, default. Manager is the orchestrator — only manager''s own @ai mentions trigger further dispatches.', ARRAY['ai', 'orchestration', 'architecture'], TRUE, (extract(epoch from now()) * 1000)::bigint, (extract(epoch from now()) * 1000)::bigint),
  ('ai-personas', 'The AI personas and their roles. engineer — implements code in a per-task workspace (shell via run_command + file tools). manager (opus) — adversarial reviewer; the only persona whose own @ai mentions dispatch others (orchestrator). planner (opus) — decomposes tasks into subtasks. reviewer (opus) — read-only code critic. default — general assistant for bare @ai. Routed by the @ai-<persona> suffix; first mention wins. Each persona is a markdown file in ai-poller/personas/ with frontmatter (model, tools, max_turns, fixer, includes).', ARRAY['ai', 'personas', 'architecture'], TRUE, (extract(epoch from now()) * 1000)::bigint, (extract(epoch from now()) * 1000)::bigint),
  ('knowledge-cards-system', 'The knowledge base is a set of searchable cards (this is one). A card = freeform content + tags + is_valid, stored in Postgres, searched by full-text or tag. Personas search the KB as required due diligence before working: `wp knowledge search "<topic>"`, `wp knowledge show <id>`. Humans author cards via `wp knowledge add`. Cards are company truth — settled decisions, conventions, domain rules. Distinct from the ChromaDB scratchpad (query_knowledge/store_knowledge), which is agent working memory. See docs/KNOWLEDGE_CARDS_DESIGN.md.', ARRAY['ai', 'knowledge-base', 'meta'], TRUE, (extract(epoch from now()) * 1000)::bigint, (extract(epoch from now()) * 1000)::bigint),
  ('persona-tools', 'Tools available to AI personas. Read: get_task, get_subtasks, get_parent_chain, get_task_comments, search_tasks. Knowledge: query_knowledge/store_knowledge (ChromaDB scratchpad), get_my_work_item/get_work_item/list_work_items. Write: create_task, delete_task (guarded); replies go via the dispatcher. Shell: run_command (engineer, reviewer — workspace-confined) or Bash(wp knowledge:*) (manager, planner, default). Files: Read/Write/Edit/Glob/Grep (engineer, reviewer). The wp CLI is available via shell.', ARRAY['workplanner', 'tools', 'ai', 'reference'], TRUE, (extract(epoch from now()) * 1000)::bigint, (extract(epoch from now()) * 1000)::bigint),
  ('wp-cli', '`wp` is the WorkPlanner CLI (Python, pipx-install from cli/). Auth via X-Internal-Key from ~/.config/workplanner/config.toml (profiles; default = prod) or WP_BASE_URL/WP_INTERNAL_KEY env. Commands mirror the UI: ls, tree, show, search, add, set, close, reopen, comment, reply, approve, deny, ai <persona>; plus `wp work-items list/show/cancel/retry` and `wp knowledge add/list/show/search/edit/rm`. Install: `make install-cli`.', ARRAY['workplanner', 'cli', 'tools', 'reference'], TRUE, (extract(epoch from now()) * 1000)::bigint, (extract(epoch from now()) * 1000)::bigint),
  ('work-items', 'A WorkItem is the unit of AI execution. Every @ai mention becomes a WorkItem row (Postgres). Two-poller pipeline: chat_handler enqueues WorkItems from mentions; work_item_handler dispatches pending ones to claude-proxy. Bounded auto-retry (5 attempts, then stops — no infinite loop). Per-task concurrency cap of 2. The reply posts as a threaded comment under the triggering mention. Inspect with `wp work-items list/show`. See docs/WORK_ITEMS_DESIGN.md.', ARRAY['ai', 'work-items', 'architecture'], TRUE, (extract(epoch from now()) * 1000)::bigint, (extract(epoch from now()) * 1000)::bigint)
ON CONFLICT (id) DO NOTHING;
